config/routes.rb
Post::Application.routes.draw do
  root :to => "jobs#home"
  get "admin" => "admin#index"
  get "submit" => "jobs#new"
  get "about" => "jobs#about"
  get "favs" => "users#favs"
  get "account" => "users#show"

  resources :jobs do
    resources :reviews
  end
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    match '/logout', :to => 'sessions#destroy'
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  default_scope :order => "name"

  has_many :reviews, :dependent => :destroy
  accepts_nested_attributes_for :reviews, :reject_if => lambda { |a| a[:eval].blank? }, :allow_destroy => true
  has_and_belongs_to_many :users

  validates_presence_of [:name, :company]
  attr_accessible :name, :company, :reviews_attributes, :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
 validates_presence_of [:rating, :start, :end, :atmosphere, :skills, :duties, :eval] 
 belongs_to :job
 belongs_to :user

 attr_accessible :rating, :start, :end, :atmosphere, :skills, :duties, :eval

  def user=(user)
    self.user_id = user.id
  end
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password

  has_and_belongs_to_many :jobs
  has_many :reviews

  validate :password_must_be_present
  
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "lulz" + salt)
  end

  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private
    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end

    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
		@jobs = Job.all
		@total_jobs = Job.count
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery
  include SessionsHelper
  
  protected
    def authorize
      # unless User.find(session[:user_id])
      unless session[:user_id] 
          redirect_to login_url, :notice => "Please log in!"
      end
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authorize, :except => [:index, :home]

  def home
  end

  def review
  end

  def about
  end

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
    @reviews = Review.find_by_job_id(params[:id])
    @new_review = @job.reviews.build
  end

  def new
    @job = Job.new
    @job.reviews.build
    @reviews = Review.find_by_job_id(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(params[:job])

    if @job.save
      redirect_to(admin_url, :notice => "Successfully added job #{@job.name} at #{@job.company}.")

    else
      render :action => "new"
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to(@job, :notice => "Job successfully updated!")
    else
      render :action => "edit"
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to(admin_url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.find
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    @job = Job.find(params[:job_id])
    @review = @job.reviews.create(params[:review])
    if @review.save
      # redirect_to(job_url(@job), :notice => "Successfully submitted job review.")
      redirect_to(job_path(@job), :notice => "Successfully submitted job review.")
    else
      render :action => "new"
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(params[:review])
      redirect_to(@review, :notice => "Review successfully updated!")
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to(admin_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize
	
	def new
	end

	def create
		if user = User.authenticate(params[:name], params[:password])
			session[:user_id] = user.id.to_s
                        sign_in user
			redirect_to jobs_url
		else
			redirect_to login_url, :alert => "Username and password do not match."
		end
	end

	def destroy
		session[:user_id] = nil
                sign_out
		redirect_to jobs_url, :notice => "You've successfully logged out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
        def favs
        end
        
	def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end
	
	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to(users_url, :notice => "Boom. User #{@user.name} has been created.")
		else
			render :action => "new"
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to(users_url, :notice => "Boom. You've updated user #{@user.name}.")
		else
			render :action => "edit"
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to(users_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/views/admin/index.html.slim
.wrapper
  .main-content
    h1 Welcome, Karlyn! You have logged in.
    p

    - if notice
      = notice

    = link_to "Add job", new_job_path
    '  |
    = link_to "Add user", new_user_path

    h2 Current jobs!

    - if @jobs.count > 0
      - @jobs.each do |job|
        .label
          = job.name
          = job.company
        .actions
          = link_to "Show", job
          = link_to "Edit", edit_job_path(job)
          = button_to "Delete this job", job, :confirm => "No fo realz?", :method => :delete, :class => :destroy

app/views/jobs/_form.html.slim
= form_for(@job) do |f|
  - if @job.errors.any?
    strong = pluralize(@job.errors.count, "error") + " -- could not save your job."
    ul
      - @job.errors.full_messages.each do |msg|
        li = msg
	
  .field
    = f.label :job_title
    = f.text_field :name

  .field
    = f.label :company
    = f.text_field :company
  
  p
  p
  p
  .submission

    h3 SUBMIT A REVIEW FOR THIS JOB:

    .field#review
      = f.fields_for :reviews do |builder|
        = builder.label :rating
        = builder.text_field :rating
        p

        = builder.label :start
        = builder.text_field :start
        p

        = builder.label :end
        = builder.text_field :end
        p

        = builder.label :atmosphere
        p
        = builder.text_area :atmosphere, :rows => 4
        p

        = builder.label :skills
        p
        = builder.text_area :skills, :rows => 4
        p

        = builder.label :duties
        p
        = builder.text_area :duties, :rows => 4
        p

        = builder.label :eval
        p
        = builder.text_area :eval, :rows => 4
        p

  .actions
    = f.submit

app/views/jobs/edit.html.slim
h1 = "Editing Project #{@job.name}"

= render "form"

= link_to "Job Details", @job
= link_to "Back", admin_path

app/views/jobs/home.html.slim
.content
  .intro
    h1 Post is like CTECs for jobs. But better.
    h4 Post allows you to search for jobs reviewed by Northwestern students and share your experiences too.
  .blurb
    | Got a job experience to share? 
    span POST 
    | it!
    p

  .actions
    .button = link_to "Browse for a job", jobs_path
    p
    .button = link_to "Submit a job review", submit_path

app/views/jobs/index.html.slim
.wrapper
  .main-content
    h1 Search for a job
    = image_tag "../img/form.gif"
    h1 Current Jobs
    .woo = image_tag "../img/box.png"
    - @jobs.each do |job|
      .block
        .title = "#{job.name} @ "
        .company = job.company
        .small-button = link_to "view", job
        .details This job has #{job.reviews.count} reviews!
    / = button_to "Add Review", reviews_path(:job_id => job)

app/views/jobs/new.html.slim
.wrapper
  .main-content
    h1 Add job!

    = render 'form'
    = link_to "Go back", admin_url

app/views/jobs/show.html.slim
.wrapper
  .main-content
    h2 Job Details
    .title = "#{@job.name} @ "
    .company = @job.company
    .rating = image_tag "../img/stars.gif"
    - if notice
            = notice
    p

    h2 Reviews

    em = @job.name
    em = @job.company
    em = @job.reviews.count

    h2 Reviews
    - @job.reviews.each do |review|
      = review.rating
      = review.eval

    = form_for [@job, @new_review] do |f|
      .field
        = f.label :rating
        = f.text_field :rating
      .field
        = f.label :start_date
        = f.text_field :start
      .field
        = f.label :end_date
        = f.text_field :end
      .field
        = f.label :atmosphere
        = f.text_area(:atmosphere, :size => "20x3")
      .field
        = f.label :skills
        = f.text_area(:skills, :size => "20x3")
      .field
        = f.label :duties
        = f.text_area(:duties, :size => "20x3")
      .field
        = f.label :eval
        = f.text_area(:eval, :size => "20x10")
      .actions
        = f.submit

app/views/layouts/_header.html.slim
.notices
  - if notice
    notice

.nav
  .branding
    | POST!
  ul
    li = link_to "Home", root_path
    li = link_to "Browse", jobs_path
    li = link_to "Submit", submit_url 
    li = link_to "About", about_url
    li#account 
      a href="#" Your Account
    - if signed_in?
      .account = link_to "Sign Out", logout_path, :method => :delete
    - else
      .account = link_to "Sign In", login_path

app/views/layouts/application.html.slim
doctype 5
html lang="en"
  head
    meta http-equiv="Content Type" content="text/html, charset=utf8"
    title Post
    link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic|Cutive|Arvo:400,700,400italic,700italic' rel='stylesheet' type='text/css'
    = stylesheet_link_tag 'index.css' 
    = javascript_include_tag '../js/jquery.min.js'
    = javascript_include_tag '../js/application.js'


  = csrf_meta_tag

  body
    == render 'layouts/header'
    = yield
    .back = link_to "Back", jobs_url

app/views/reviews/_form.html.slim
= form_for(@review) do |f|
  - if @review.errors.any?
    strong = pluralize(@review.errors.count, "error") + " -- could not save your review."
    ul
      - @review.errors.full_messages.each do |msg|
        li = msg


  fieldset#newReview
    .field
      = f.label :rating
      = f.text_field :rating
    .field
      = f.label :start_date
      = f.text_field :start
    .field
      = f.label :end_date
      = f.text_field :end
    .field
      = f.label :atmosphere
      = f.text_area(:atmosphere, :size => "20x3")
    .field
      = f.label :skills
      = f.text_area(:skills, :size => "20x3")
    .field
      = f.label :duties
      = f.text_area(:duties, :size => "20x3")
    .field
      = f.label :eval
      = f.text_area(:eval, :size => "20x10")
    .actions
      = f.submit

app/views/reviews/new.html.slim
= render 'form'
= link_to "Go back", jobs_url

app/views/users/_form.html.slim
= form_for(@user) do |f|
	- if @user.errors.any?
		strong = pluralize(@user.errors.count, "error") + " -- could not save user."
		ul
			- @user.errors.full_messages.each do |msg|
				li = msg
	
	fieldset#newUser
		.field
			= f.label :name
			= f.text_field :name

		.field
			= f.label :password
			= f.password_field :password, :size => 20

		.field
			= f.label :password_confirmation
			= f.password_field :password_confirmation, :size => 20
		.field
			= f.label :email
			= f.email_field :email, :size => 40

		.actions
			= f.submit

app/views/users/edit.html.slim
= render "form"

= link_to "Show", @user
= link_to "Back", users_path

app/views/users/index.html.slim
h1 Userszszszszsz

- if notice
	= notice

= link_to "Add someone to the club", new_user_path
p
- @users.each do |user|
	.label 	= user.name
	.actions 
		= link_to "Show", user
		= link_to "Edit", edit_user_path(user)
		= button_to "Delete this user", user, :confirm => "No but really?", :method => :delete, :class => :destroy

app/views/users/new.html.slim
h1 Add a user!

= render 'form'
= link_to "Go back", users_path

app/views/users/show.html.slim
- if notice
	= notice

strong Name:
= @user.name

p

strong Password (jk you can't really see it)
= @user.hashed_password

= link_to "Edit", edit_user_path(@user)
= link_to "Back", users_path